05:04:57 PM: DEBUG [logger_base.py:12] Mensaje a nivel debug
05:04:57 PM: INFO [logger_base.py:13] Mensaje a nivel info
05:04:57 PM: WARNING [logger_base.py:14] Mensaje a nivel warning
05:04:57 PM: ERROR [logger_base.py:15] Mensaje a nivel error
05:04:57 PM: CRITICAL [logger_base.py:16] Mensaje a nivel critical
02:30:39 PM: DEBUG [Persona.py:53] 
            Idd Persona: 1, 
            Nombre: Juan, 
            Apellido: Perez, 
            Email: jperez@mail.com
        
02:35:40 PM: DEBUG [Persona.py:53] 
            Idd Persona: 1, 
            Nombre: Juan, 
            Apellido: Perez, 
            Email: jperez@mail.com
        
02:38:22 PM: DEBUG [Persona.py:55] 
            Idd Persona: 1, 
            Nombre: Juan, 
            Apellido: Perez, 
            Email: jperez@mail.com
        
02:38:22 PM: DEBUG [Persona.py:57] 
            Idd Persona: Jose, 
            Nombre: Lepez, 
            Apellido: ljose@mail.com, 
            Email: None
        
02:39:29 PM: DEBUG [Persona.py:55] 
            Id Persona: 1, 
            Nombre: Juan, 
            Apellido: Perez, 
            Email: jperez@mail.com
        
02:39:29 PM: DEBUG [Persona.py:57] 
            Id Persona: Jose, 
            Nombre: Lepez, 
            Apellido: ljose@mail.com, 
            Email: None
        
02:41:15 PM: DEBUG [Persona.py:55] 
            Id Persona: 1, 
            Nombre: Juan, 
            Apellido: Perez, 
            Email: jperez@mail.com
        
02:41:15 PM: DEBUG [Persona.py:57] 
            Id Persona: None, 
            Nombre: Jose, 
            Apellido: Lepez, 
            Email: ljose@mail.com
        
02:41:15 PM: DEBUG [Persona.py:59] 
            Id Persona: 1, 
            Nombre: None, 
            Apellido: None, 
            Email: None
        
04:02:44 PM: DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x00000234E5352790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
04:04:05 PM: ERROR [conexion.py:28] Ocurrio un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgre"

04:05:00 PM: DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x0000029899A72790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
04:05:00 PM: ERROR [conexion.py:41] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
04:06:39 PM: DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x00000285B4E52790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
04:06:39 PM: ERROR [conexion.py:41] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
04:07:18 PM: DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000002164D5B2790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
04:07:18 PM: DEBUG [conexion.py:38] Se abrio correctamente el cursor: <cursor object at 0x000002164F31BA00; closed: 0>
01:39:25 PM: DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x0000028A488E17A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
01:39:25 PM: DEBUG [conexion.py:38] Se abrio correctamente el cursor: <cursor object at 0x0000028A4A7AD620; closed: 0>
01:40:01 PM: DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000001F01FE017A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
01:40:01 PM: DEBUG [conexion.py:38] Se abrio correctamente el cursor: <cursor object at 0x000001F022031620; closed: 0>
01:40:01 PM: DEBUG [persona_dao.py:35] 
            Id Persona: 1, 
            Nombre: Juan Carlos, 
            Apellido: Roldan, 
            Email: jcroldan@mail.com
        
01:40:01 PM: DEBUG [persona_dao.py:35] 
            Id Persona: 2, 
            Nombre: Carla
, 
            Apellido: Gomez, 
            Email: kgomez@mail.com

        
01:40:01 PM: DEBUG [persona_dao.py:35] 
            Id Persona: 8, 
            Nombre: Carlos, 
            Apellido: Lara, 
            Email: clara@gmail.com
        
01:40:01 PM: DEBUG [persona_dao.py:35] 
            Id Persona: 9, 
            Nombre: Marcos, 
            Apellido: Canto, 
            Email: mcanto@gmail.com
        
01:40:01 PM: DEBUG [persona_dao.py:35] 
            Id Persona: 10, 
            Nombre: Marcelo, 
            Apellido: Cuenca, 
            Email: cuencaM@gmail.com
        
01:40:01 PM: DEBUG [persona_dao.py:35] 
            Id Persona: 12, 
            Nombre: Maria, 
            Apellido: Esparza, 
            Email: mesparrza@gmail.com
        
01:40:01 PM: DEBUG [persona_dao.py:35] 
            Id Persona: 13, 
            Nombre: Carlos, 
            Apellido: Lara, 
            Email: clara@mail.com
        
01:40:01 PM: DEBUG [persona_dao.py:35] 
            Id Persona: 14, 
            Nombre: Jorge, 
            Apellido: Prol, 
            Email: jprol@mail.com
        
01:40:01 PM: DEBUG [persona_dao.py:35] 
            Id Persona: 15, 
            Nombre: Alex, 
            Apellido: Rojas, 
            Email: arojas@mail.com
        
01:48:46 PM: DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000001DD57CC17A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
01:48:46 PM: DEBUG [conexion.py:38] Se abrio correctamente el cursor: <cursor object at 0x000001DD59B51620; closed: 0>
01:48:46 PM: DEBUG [persona_dao.py:38] Persona insertada: 
            Id Persona: None, 
            Nombre: Pedro, 
            Apellido: Romero, 
            Email: promero@mail.com
        
01:48:46 PM: DEBUG [persona_dao.py:46] Personas insertadas: 1
01:50:48 PM: DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000002B5AE3717A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
01:50:48 PM: DEBUG [conexion.py:38] Se abrio correctamente el cursor: <cursor object at 0x000002B5B0555540; closed: 0>
01:50:48 PM: DEBUG [persona_dao.py:38] Persona insertada: 
            Id Persona: None, 
            Nombre: Omero, 
            Apellido: Ramos, 
            Email: omeror@mail.com
        
01:50:48 PM: DEBUG [persona_dao.py:46] Personas insertadas: 1
02:08:28 PM: DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000001CC630917A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
02:08:28 PM: DEBUG [conexion.py:38] Se abrio correctamente el cursor: <cursor object at 0x000001CC652E1620; closed: 0>
02:08:28 PM: DEBUG [persona_dao.py:46] Persona actualizada: 
            Id Persona: 1, 
            Nombre: Juan Jose, 
            Apellido: Pena, 
            Email: jjpena@mail.com
        
02:08:28 PM: DEBUG [persona_dao.py:54] Personas actualizadas: 1
02:49:58 PM: DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000001E508EC17A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
02:49:58 PM: DEBUG [conexion.py:38] Se abrio correctamente el cursor: <cursor object at 0x000001E50AD65620; closed: 0>
02:49:58 PM: DEBUG [persona_dao.py:55] Los objetos eliminados son: 
            Id Persona: 13, 
            Nombre: None, 
            Apellido: None, 
            Email: None
        
02:49:58 PM: DEBUG [persona_dao.py:62] Personas eliminadas: 1
02:50:37 PM: DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x0000020B975E17A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
02:50:37 PM: DEBUG [conexion.py:38] Se abrio correctamente el cursor: <cursor object at 0x0000020B99455620; closed: 0>
02:50:37 PM: DEBUG [persona_dao.py:55] Los objetos eliminados son: 
            Id Persona: 8, 
            Nombre: None, 
            Apellido: None, 
            Email: None
        
02:50:37 PM: DEBUG [persona_dao.py:62] Personas eliminadas: 1
03:01:29 PM: DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000001D9E86017A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:01:29 PM: DEBUG [conexion.py:38] Se abrio correctamente el cursor: <cursor object at 0x000001D9EA475620; closed: 0>
03:01:29 PM: DEBUG [persona_dao.py:78] 
            Id Persona: 1, 
            Nombre: Juan Jose, 
            Apellido: Pena, 
            Email: jjpena@mail.com
        
03:01:29 PM: DEBUG [persona_dao.py:78] 
            Id Persona: 2, 
            Nombre: Carla
, 
            Apellido: Gomez, 
            Email: kgomez@mail.com

        
03:01:29 PM: DEBUG [persona_dao.py:78] 
            Id Persona: 9, 
            Nombre: Marcos, 
            Apellido: Canto, 
            Email: mcanto@gmail.com
        
03:01:29 PM: DEBUG [persona_dao.py:78] 
            Id Persona: 10, 
            Nombre: Marcelo, 
            Apellido: Cuenca, 
            Email: cuencaM@gmail.com
        
03:01:29 PM: DEBUG [persona_dao.py:78] 
            Id Persona: 12, 
            Nombre: Maria, 
            Apellido: Esparza, 
            Email: mesparrza@gmail.com
        
03:01:29 PM: DEBUG [persona_dao.py:78] 
            Id Persona: 14, 
            Nombre: Jorge, 
            Apellido: Prol, 
            Email: jprol@mail.com
        
03:01:29 PM: DEBUG [persona_dao.py:78] 
            Id Persona: 15, 
            Nombre: Alex, 
            Apellido: Rojas, 
            Email: arojas@mail.com
        
03:01:29 PM: DEBUG [persona_dao.py:78] 
            Id Persona: 16, 
            Nombre: Pedro, 
            Apellido: Romero, 
            Email: promero@mail.com
        
03:01:29 PM: DEBUG [persona_dao.py:78] 
            Id Persona: 17, 
            Nombre: Omero, 
            Apellido: Ramos, 
            Email: omeror@mail.com
        
